### ISSUE TITLE
Tailwindcss v1.0.0

### ISSUE THREAD

**Issue by eshimischi** [ky-is/tailwind-color-palette#1]
Hello, thanks a lot for your very useful plugin for Tailwindcss. Would you please update it to work with upcoming 1.0.0 version of Tailwindcss? https://github.com/tailwindcss/tailwindcss/releases/tag/v1.0.0-beta.1 here is the list of changes.

Thanks a lot!

**Comment by ky-is** [comment]
I haven't had a chance to try the 1.0 beta yet, but I should this week. Thanks for bringing this up!

**Comment by ky-is** [comment]
https://github.com/ky-is/tailwind-color-palette/tree/v1.0.0-beta.1 is available with the `@next` tag from npm to try!

**Comment by eshimischi** [comment]
> https://github.com/ky-is/tailwind-color-palette/tree/v1.0.0-beta.1 is available with the `@next` tag from npm to try!

you are legend! thanks

**Comment by eshimischi** [comment]
> https://github.com/ky-is/tailwind-color-palette/tree/v1.0.0-beta.1 is available with the `@next` tag from npm to try!

hi. Tailwind v1.0 is released now [ver 1.0.1](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.0.1)

**Comment by ky-is** [comment]
Released, thank you!
