### ISSUE TITLE
Ability to generate 'bg'-* colors

### ISSUE THREAD

**Issue by D4rkMindz** [ky-is/tailwind-color-palette#2]
Hi there.

First of all, thanks for creating such a useful tool.

Now that i am using that tool, i found out, that this tool is not able to generate the bg-<colors>-<scale> classes.

How may i help you implementing this feature to generate also the named classes?

**Comment by ky-is** [comment]
Hey, glad you're enjoying it!

This utility just creates the color definitions that Tailwind then uses to generate the actual classes like `text-brand-900`, `bg-brand-100`, etc. So if `bg-*-x00` isn't working, there may be an issue with your configuration.

Check out the documentation here: https://tailwindcss.com/docs/background-color/#customizing, and let me know if you're still having any issues, thanks!
